### ISSUE TITLE
unusable augmented embedder: values are nan

### ISSUE THREAD

**Issue by chris-aeviator** [sjunhongshen/Tag-LLM#4]
Task: Language (domain_tag.yaml)
Model: llama7b (huggyllama)
Python 3.10 (same on 3.9)
GPU: RTX A6000 Ada

When training the model (I tried many training runs & different datasets) the embeddings turn out always nan (not a number). The trained model will only output garbage (\x04 tokens - token id 7 - instead of text, a single \x02 - token id 5 - token at the end). I'm using TagLLamaForCausalLM.from_pretrained to load the model, but also see this in the exp/Language/[...]/embedding_weights.npy file 

![grafik](https://github.com/sjunhongshen/Tag-LLM/assets/11522213/b6438293-25df-4015-94d1-0ab5b33717da)

Update:
This is interesting, it seems to happen gradually

Step 0 (initial weights) to 2
![grafik](https://github.com/sjunhongshen/Tag-LLM/assets/11522213/4f981419-a7c8-42ed-acf8-67a87aa79fc1)

Loss step 0:  tensor(9.0469, device='cuda:0', dtype=torch.float16, grad_fn=\<AddBackward0\>)
Loss step 1:  tensor(nan, device='cuda:0', dtype=torch.float16, grad_fn=\<AddBackward0\>)

I can see that there are no input gradients coming to the augmented embedder when registering a backward hook to it, I'm unsure if that's what's supposed to happen

**Comment by sjunhongshen** [comment]
sorry, this was due to loading the model in 8 bits, just commented out line 207-208 in train.py. this is fixed in main branch. thank you!
