### ISSUE TITLE
TypeError: compute_metrics() got an unexpected keyword argument 'special_tokens'

### ISSUE THREAD

**Issue by AlienKevin** [sjunhongshen/Tag-LLM#5]
In `metrics.py`, `get_compute_metrics_fn` tries to do a partial application with a keyword argument called `special_tokens`. However, the `compute_metrics` function does not have this argument. It only has something called `gist_token` but somehow that argument is not even used and is deleted immediately on the first line.

```
def get_compute_metrics_fn(
    special_tokens: int, tokenizer: PreTrainedTokenizer, args: Arguments
) -> Callable:
    return functools.partial(
        compute_metrics, special_tokens=special_tokens, tokenizer=tokenizer, args=args
    )
```

```
def compute_metrics(
    eval_preds: EvalPrediction,
    gist_token: int,
    tokenizer: PreTrainedTokenizer,
    args: Arguments,
    output_file: Optional[str] = None,
) -> Metrics:
    del gist_token
    ...
```

**Comment by sjunhongshen** [comment]
Thanks! Evaluation should be performed separately using `generation.py` or `infer_regression.py`, but not directly inside `train.py`.
